// AUTO-GENERATED by `pnpm gen:seeds` from data/seeds/topics.ts — DO NOT EDIT BY HAND.
// Re-run the script (needs ANTHROPIC_API_KEY in .env) to (re)generate, then review the diff
// before committing.
import type { StorySeed } from './types';

export const GENERATED_SEEDS: StorySeed[] = [
  {
    "id": "shou-zhu-dai-tu",
    "title": "守株待兔",
    "titleEn": "Waiting by the Tree Stump",
    "blurb": "A farmer gets one lucky meal and then waits forever for more.",
    "setting": "Long ago, in a small farming village with a tree stump at the edge of a field.",
    "characters": [
      "a lazy farmer who hopes for easy luck",
      "a rabbit that runs into the stump by accident"
    ],
    "beats": [
      "A farmer works hard in his field every day but wishes for an easier life.",
      "One day a rabbit crashes into a tree stump and dies, so the farmer takes it home for a free meal.",
      "The farmer decides farming is unnecessary and waits by the stump every day for more rabbits.",
      "No more rabbits come, and his field fills with weeds and goes to ruin.",
      "The farmer becomes hungry and ashamed, learning that luck cannot replace hard work."
    ],
    "themeHints": [
      "luck",
      "hard work",
      "foolishness"
    ],
    "source": "work",
    "publicDomain": true,
    "attribution": "《韩非子》 (Han Feizi) — public domain"
  },
  {
    "id": "ke-zhou-qiu-jian",
    "title": "刻舟求剑",
    "titleEn": "Carving the Boat to Find the Sword",
    "blurb": "A man drops his sword in a river and marks the boat to find it later, never realizing the boat has moved on.",
    "setting": "On a small boat crossing a wide river in ancient China.",
    "characters": [
      "a traveler crossing the river with his sword",
      "a boatman who rows the traveler across"
    ],
    "beats": [
      "A man rides in a boat across a river, carrying his sword at his side.",
      "The sword slips loose and falls into the deep water.",
      "The man pulls out a knife and carves a mark on the boat where the sword went down.",
      "The boat keeps moving and reaches the far shore.",
      "The man dives below his carved mark, but the sword is gone because the boat moved while the sword stayed behind."
    ],
    "themeHints": [
      "adaptability",
      "change",
      "folly"
    ],
    "source": "work",
    "publicDomain": true,
    "attribution": "《吕氏春秋》 (Lüshi Chunqiu) — public domain"
  },
  {
    "id": "hua-she-tian-zu",
    "title": "画蛇添足",
    "titleEn": "Drawing Legs on a Snake",
    "blurb": "A fast artist learns that showing off can turn a win into a loss.",
    "setting": "Long ago, at a gathering where guests compete for a prize of wine.",
    "characters": [
      "a quick, boastful man who draws fastest",
      "a slower, steady man who finishes second"
    ],
    "beats": [
      "Several men compete to draw a snake, and the fastest finisher wins a pot of wine.",
      "The quick man finishes first and, feeling proud, adds legs to his snake to show off.",
      "The second man finishes his simple snake and points out that snakes have no legs.",
      "The second man takes the wine, and the boastful man loses by adding something unnecessary."
    ],
    "themeHints": [
      "overdoing",
      "moderation",
      "pride"
    ],
    "source": "work",
    "publicDomain": true,
    "attribution": "《战国策》 (Strategies of the Warring States) — public domain"
  },
  {
    "id": "yu-gong-yi-shan",
    "title": "愚公移山",
    "titleEn": "The Old Man Who Moved the Mountains",
    "blurb": "An old man decides to dig away two mountains blocking his home, and his family will not stop until they are gone.",
    "setting": "Long ago in ancient China, a small village sits between two huge mountains that block the way out.",
    "characters": [
      "a stubborn old man who refuses to give up",
      "his loyal family who agrees to help him dig",
      "a wise man who doubts the plan can work",
      "the gods in heaven who watch over people"
    ],
    "beats": [
      "Two huge mountains stand in front of the old man's home and make travel very hard.",
      "The old man tells his family they will dig the mountains away and carry the rocks to the sea.",
      "A neighbor laughs and says they are too old and weak to ever finish the job.",
      "The old man answers that his children and their children will keep digging, so the mountains will shrink while his family never runs out of workers.",
      "The gods hear his words and are moved by his determination, so they send spirits to carry the mountains far away."
    ],
    "themeHints": [
      "perseverance",
      "determination",
      "faith"
    ],
    "source": "work",
    "publicDomain": true,
    "attribution": "《列子》 (Liezi) — public domain"
  },
  {
    "id": "zi-xiang-mao-dun",
    "title": "自相矛盾",
    "titleEn": "The Spear and the Shield",
    "blurb": "A seller makes two big promises at the same time, and one quick question reveals his lie.",
    "setting": "Long ago, at a busy market stall where a man sells weapons.",
    "characters": [
      "a peddler who boasts loudly about his goods",
      "a calm bystander who asks a sharp question"
    ],
    "beats": [
      "A peddler sets up a stall to sell spears and shields.",
      "He tells the crowd his shield can block any spear.",
      "Then he says his spear can pierce any shield.",
      "A bystander asks what happens if the spear strikes the shield.",
      "The peddler cannot answer and stands silent."
    ],
    "themeHints": [
      "contradiction",
      "honesty",
      "cleverness"
    ],
    "source": "work",
    "publicDomain": true,
    "attribution": "《韩非子》 (Han Feizi) — public domain"
  },
  {
    "id": "ya-miao-zhu-zhang",
    "title": "揠苗助长",
    "titleEn": "Pulling Up the Seedlings",
    "blurb": "An impatient farmer tries to help his rice grow faster, but ruins it all.",
    "setting": "Long ago, in a small farming village with a rice paddy.",
    "characters": [
      "an impatient farmer who wants quick results",
      "the farmer's son, who sees the result"
    ],
    "beats": [
      "A farmer plants rice seedlings and waits for them to grow taller, but he feels they grow too slowly.",
      "He goes to the field and pulls every seedling up a little, one by one, thinking this will help them grow faster.",
      "He comes home tired but proud, and tells his family he has helped the plants grow.",
      "His son rushes to the field the next day and finds all the seedlings withered and dead.",
      "The farmer learns that forcing something to grow faster only destroys it."
    ],
    "themeHints": [
      "patience",
      "natural-growth",
      "overreaching"
    ],
    "source": "work",
    "publicDomain": true,
    "attribution": "《孟子》 (Mengzi / Mencius) — public domain"
  },
  {
    "id": "wang-yang-bu-lao",
    "title": "亡羊补牢",
    "titleEn": "Mending the Pen After the Sheep Is Lost",
    "blurb": "A shepherd learns that fixing a problem late is still better than never fixing it.",
    "setting": "Long ago at a small farm in the countryside.",
    "characters": [
      "a shepherd who keeps sheep in a pen",
      "a wise neighbor who warns the shepherd"
    ],
    "beats": [
      "A wolf gets into the pen through a hole and takes one sheep.",
      "A neighbor tells the shepherd to fix the hole, but the shepherd says it is too late and ignores him.",
      "The wolf comes back through the same hole and takes another sheep.",
      "The shepherd feels sorry and finally mends the hole.",
      "No more sheep are lost, and he understands it is never too late to fix a problem."
    ],
    "themeHints": [
      "responsibility",
      "delay",
      "repair"
    ],
    "source": "work",
    "publicDomain": true,
    "attribution": "《战国策》 (Strategies of the Warring States) — public domain"
  },
  {
    "id": "hu-jia-hu-wei",
    "title": "狐假虎威",
    "titleEn": "The Fox Borrows the Tigers Might",
    "blurb": "A clever fox escapes a hungry tiger by pretending the other animals fear her.",
    "setting": "In a forest in ancient times.",
    "characters": [
      "a hungry tiger",
      "a clever fox"
    ],
    "beats": [
      "A tiger catches a fox and wants to eat her.",
      "The fox claims heaven made her the king of all animals and warns the tiger he will be punished if he eats her.",
      "The fox dares the tiger to follow behind her and watch the other animals run away.",
      "The tiger agrees and walks behind her through the forest.",
      "The animals flee at the sight of the tiger, but the tiger believes they fear the fox."
    ],
    "themeHints": [
      "cleverness",
      "deception",
      "power"
    ],
    "source": "work",
    "publicDomain": true,
    "attribution": "《战国策》 (Strategies of the Warring States) — public domain"
  },
  {
    "id": "ye-gong-hao-long",
    "title": "叶公好龙",
    "titleEn": "Lord Ye Who Loved Dragons",
    "blurb": "A lord who decorates everything with dragons gets a surprise visit from a real one.",
    "setting": "In ancient China, in the grand house of a wealthy lord.",
    "characters": [
      "a lord who claims to love dragons",
      "a real dragon who hears about the lord's devotion"
    ],
    "beats": [
      "Lord Ye tells everyone he loves dragons and covers his walls, pillars, and furniture with dragon carvings and paintings.",
      "A real dragon in heaven hears about this and feels moved that such a devoted admirer exists.",
      "The dragon descends from the sky and comes to visit Lord Ye's house.",
      "Lord Ye sees the real dragon and is so terrified that he runs away and hides.",
      "Everyone realizes Lord Ye only loved the image of dragons, not real dragons."
    ],
    "themeHints": [
      "hypocrisy",
      "appearances",
      "true vs false love"
    ],
    "allowNames": [
      "叶公"
    ],
    "source": "work",
    "publicDomain": true,
    "attribution": "《新序》 (Xinxu), 刘向 — public domain"
  },
  {
    "id": "kong-rong-rang-li",
    "title": "孔融让梨",
    "titleEn": "Kong Rong Gives Up the Pears",
    "blurb": "A little boy chooses the smallest pear and teaches his family a lesson in kindness.",
    "setting": "In an old Chinese family home long ago.",
    "characters": [
      "four-year-old Kong Rong",
      "Kong Rong's elder brothers"
    ],
    "beats": [
      "A plate of pears is brought for the children to share.",
      "Kong Rong is told he may pick first.",
      "He takes the smallest pear and gives the bigger ones to his elder brothers.",
      "When asked why, he says the young should respect their elders.",
      "The family is moved and praises his courtesy."
    ],
    "themeHints": [
      "courtesy",
      "modesty",
      "respect"
    ],
    "allowNames": [
      "孔融"
    ],
    "source": "history"
  },
  {
    "id": "cao-chong-cheng-xiang",
    "title": "曹冲称象",
    "titleEn": "Cao Chong Weighs the Elephant",
    "blurb": "A young boy solves a puzzle that stumps all the grown-ups: how do you weigh an elephant?",
    "setting": "Long ago in China, at a royal court near a river.",
    "characters": [
      "a clever young boy named Cao Chong",
      "a powerful lord who is Cao Chong's father",
      "a giant elephant brought as a gift",
      "officials who cannot agree how to weigh the elephant"
    ],
    "beats": [
      "A visitor brings a huge elephant to the lord, and everyone wants to know how much it weighs.",
      "The officials argue but cannot find a scale big enough or a way to weigh the animal.",
      "Young Cao Chong says to lead the elephant onto a boat and mark where the water reaches on the side.",
      "He then has the elephant taken off and stones loaded onto the boat until the water reaches the same mark.",
      "The stones are weighed one by one and added up, giving the weight of the elephant, and everyone praises the boy's cleverness."
    ],
    "themeHints": [
      "cleverness",
      "problem-solving",
      "wisdom"
    ],
    "allowNames": [
      "曹冲"
    ],
    "source": "history"
  },
  {
    "id": "wan-bi-gui-zhao",
    "title": "完璧归赵",
    "titleEn": "Returning the Jade Intact to Zhao",
    "blurb": "A clever envoy risks his life to protect a priceless jade from a greedy king.",
    "setting": "In ancient China, during a tense rivalry between two states, Zhao and Qin.",
    "characters": [
      "Lin Xiangru, a brave and quick-witted envoy",
      "the powerful King of Qin, who is greedy and deceitful",
      "the King of Zhao, who fears losing his treasure"
    ],
    "beats": [
      "The King of Zhao sends Lin Xiangru with a priceless jade to Qin, after the King of Qin promises to trade cities for it.",
      "The King of Qin receives the jade but shows no intention of giving up any cities.",
      "Lin Xiangru claims the jade has a flaw and takes it back into his own hands.",
      "He threatens to smash the jade unless the king keeps his promise, then secretly sends the jade safely back to Zhao.",
      "The King of Qin admires Lin Xiangru's courage and lets him return unharmed."
    ],
    "themeHints": [
      "courage",
      "cleverness",
      "integrity"
    ],
    "allowNames": [
      "蔺相如",
      "赵"
    ],
    "source": "history"
  },
  {
    "id": "wo-xin-chang-dan",
    "title": "卧薪尝胆",
    "titleEn": "Sleeping on Firewood, Tasting Gall",
    "blurb": "A defeated king endures years of hardship and never forgets his shame until he wins back his kingdom.",
    "setting": "Long ago in ancient China, two rival kingdoms are at war.",
    "characters": [
      "a defeated king who refuses to give up",
      "a powerful enemy king who won the first war",
      "loyal people of the defeated kingdom"
    ],
    "beats": [
      "The king loses a war and is forced to serve his enemy in shame.",
      "He returns home determined to rebuild and never forget his defeat.",
      "He sleeps on rough firewood and tastes bitter gall every day to remind himself of his pain.",
      "He trains his people and strengthens his kingdom for many years.",
      "Finally he attacks and defeats the enemy king, taking back his honor."
    ],
    "themeHints": [
      "perseverance",
      "patience",
      "determination"
    ],
    "allowNames": [
      "勾践"
    ],
    "source": "history"
  },
  {
    "id": "zao-bi-tou-guang",
    "title": "凿壁偷光",
    "titleEn": "Boring the Wall to Borrow the Light",
    "blurb": "A poor boy finds a clever way to keep reading after dark.",
    "setting": "In ancient China, a poor farming village where lamps need costly oil.",
    "characters": [
      "Kuang Heng, a poor boy who loves to study but cannot afford lamp oil",
      "a richer neighbor whose house has a lamp at night"
    ],
    "beats": [
      "Kuang Heng works hard by day and wants to read at night, but has no oil for a lamp.",
      "He notices light from his neighbor's house shining through a crack in the wall.",
      "He bores a small hole in the wall so a thin beam of light enters his room.",
      "He uses the borrowed light to read every night and studies without giving up.",
      "Kuang Heng grows up to become a very learned and respected man."
    ],
    "themeHints": [
      "dedication",
      "study",
      "cleverness"
    ],
    "allowNames": [
      "匡衡"
    ],
    "source": "history"
  },
  {
    "id": "tie-chu-mo-zhen",
    "title": "铁杵磨针",
    "titleEn": "Grinding an Iron Rod into a Needle",
    "blurb": "A restless boy learns a big lesson from an old woman and a very thick iron rod.",
    "setting": "Long ago in China, near a quiet river and a small village.",
    "characters": [
      "a clever but restless young boy who dislikes studying",
      "a patient old woman who works steadily without complaint"
    ],
    "beats": [
      "The boy sneaks away from his books and wanders outside instead of studying.",
      "By the river he sees an old woman rubbing a thick iron rod against a stone.",
      "He asks what she is doing, and she says she is grinding it into a sewing needle.",
      "The boy laughs and says that is impossible, but she answers that steady work every day can finish any task.",
      "Ashamed by her patience, the boy returns home and studies hard from that day on."
    ],
    "themeHints": [
      "persistence",
      "patience",
      "study"
    ],
    "allowNames": [
      "李白"
    ],
    "source": "history"
  },
  {
    "id": "wen-ji-qi-wu",
    "title": "闻鸡起舞",
    "titleEn": "Rising at the Rooster’s Crow to Train",
    "blurb": "Two friends hear a rooster crow at dawn and turn it into a daily call to train their bodies and minds.",
    "setting": "In ancient China, during a time when the country was troubled and needed capable leaders.",
    "characters": [
      "Zu Ti, a young man who dreams of serving his country",
      "Zu Ti's close friend and roommate, who shares the same ambition"
    ],
    "beats": [
      "Zu Ti and his friend share a room and a strong wish to help their country one day.",
      "One night a rooster crows long before dawn, waking the two friends.",
      "Instead of going back to sleep, Zu Ti urges his friend to get up and practice swordplay.",
      "From that day on, whenever the rooster crows, the two friends rise and train together.",
      "Their years of daily discipline make them strong and skilled, ready to serve their country."
    ],
    "themeHints": [
      "diligence",
      "ambition",
      "self-discipline"
    ],
    "allowNames": [
      "祖逖"
    ],
    "source": "history"
  },
  {
    "id": "jing-di-zhi-wa",
    "title": "井底之蛙",
    "titleEn": "The Frog in the Well",
    "blurb": "A frog thinks his little well is the whole world, until a turtle tells him about the sea.",
    "setting": "Long ago, at the bottom of a shallow well near the sea.",
    "characters": [
      "a small frog who lives in a well and feels very proud",
      "a wise sea turtle who has traveled far"
    ],
    "beats": [
      "The frog lives at the bottom of a well and believes it is the entire world.",
      "A sea turtle stops by the well, and the frog proudly shows off his tiny home.",
      "The turtle describes the endless, deep ocean he comes from.",
      "The frog realizes his well is nothing compared to the sea and falls silent."
    ],
    "themeHints": [
      "perspective",
      "humility",
      "narrow-mindedness"
    ],
    "source": "work",
    "publicDomain": true,
    "attribution": "《庄子》 (Zhuangzi) — public domain"
  },
  {
    "id": "lan-yu-chong-shu",
    "title": "滥竽充数",
    "titleEn": "Filling the Ranks of the Flute Players",
    "blurb": "A man who cannot play a note hides in the royal band, until the new king asks everyone to play alone.",
    "setting": "Long ago in a Chinese royal palace, where a huge band of musicians plays for the king.",
    "characters": [
      "Mr. Nanguo, a man who cannot play the yu but wants an easy salary",
      "the old king, who likes hearing all the musicians play together",
      "the new king, who wants each musician to play a solo"
    ],
    "beats": [
      "The old king hires a large royal band of three hundred yu players to play together.",
      "Mr. Nanguo joins the band even though he cannot play, and pretends to blow his instrument among the crowd.",
      "Because the group is so big, no one notices he is faking, and he draws a salary for years.",
      "The old king dies, and the new king says every player must perform a solo one by one.",
      "Afraid of being exposed, Mr. Nanguo runs away in panic before his turn comes."
    ],
    "themeHints": [
      "deception",
      "scrutiny",
      "consequences"
    ],
    "allowNames": [
      "南郭先生"
    ],
    "source": "work",
    "publicDomain": true,
    "attribution": "《韩非子》 (Han Feizi) — public domain"
  },
  {
    "id": "yan-er-dao-ling",
    "title": "掩耳盗铃",
    "titleEn": "Covering the Ears to Steal the Bell",
    "blurb": "A thief tries to steal a huge bell, but his plan to stay quiet only fools himself.",
    "setting": "Long ago, in a village with a wealthy family's courtyard.",
    "characters": [
      "a greedy thief who wants to steal a big bell",
      "the owner of the bell and the household"
    ],
    "beats": [
      "A thief spots a large, valuable bell outside a rich family's gate and decides to steal it.",
      "The bell is too heavy to carry easily, so he tries to break it apart with a hammer.",
      "The hammer strikes the bell and it rings loudly, scaring the thief that someone will hear.",
      "He stuffs his fingers in his own ears, thinking if he cannot hear the bell, no one else can either.",
      "The loud ringing wakes the household, and the thief is quickly caught."
    ],
    "themeHints": [
      "self-deception",
      "foolishness",
      "truth"
    ],
    "source": "work",
    "publicDomain": true,
    "attribution": "《吕氏春秋》 (Lüshi Chunqiu) — public domain"
  },
  {
    "id": "sai-weng-shi-ma",
    "title": "塞翁失马",
    "titleEn": "The Old Man of the Frontier Loses His Horse",
    "blurb": "An old man near the border loses his horse — but is the loss really bad luck, or could it be good luck in disguise?",
    "setting": "Long ago, at a frontier town near the border of ancient China.",
    "characters": [
      "a calm and wise old man who lives near the frontier",
      "his son, a young man who loves riding horses",
      "the neighbors, who always react with joy or worry"
    ],
    "beats": [
      "The old man's horse runs away into the barbarian lands, and the neighbors feel sorry for him, but he says maybe it is not a bad thing.",
      "The horse comes back leading a beautiful wild horse, and the neighbors congratulate him, but he says maybe it is not a good thing.",
      "The old man's son tries to ride the wild horse, falls off, and breaks his leg, and the neighbors feel sorry for him, but he again says maybe it is not a bad thing.",
      "A war breaks out and all the healthy young men are drafted, but the son is spared because of his broken leg, and he survives while many others do not."
    ],
    "themeHints": [
      "fortune",
      "misfortune",
      "wisdom"
    ],
    "allowNames": [
      "塞翁"
    ],
    "source": "work",
    "publicDomain": true,
    "attribution": "《淮南子》 (Huainanzi) — public domain"
  },
  {
    "id": "nan-yuan-bei-zhe",
    "title": "南辕北辙",
    "titleEn": "Heading South by Steering North",
    "blurb": "A traveler with the fastest horses and the best driver speeds confidently in the wrong direction.",
    "setting": "On the roads of ancient China, during a time when people traveled by chariot between states.",
    "characters": [
      "a traveler heading to the southern state of Chu",
      "a friend who sees him going the wrong way"
    ],
    "beats": [
      "A traveler announces he is going south to the state of Chu but drives his chariot north.",
      "A friend points out that Chu lies to the south, not the north.",
      "The traveler is not worried and boasts that his horses are very fast.",
      "The friend warns that faster horses will only take him farther from Chu.",
      "The traveler replies that he has plenty of money and a skilled driver, still heading north and moving ever farther from his goal."
    ],
    "themeHints": [
      "direction",
      "stubbornness",
      "wisdom"
    ],
    "source": "work",
    "publicDomain": true,
    "attribution": "《战国策》 (Strategies of the Warring States) — public domain"
  },
  {
    "id": "zhao-san-mu-si",
    "title": "朝三暮四",
    "titleEn": "Three in the Morning, Four at Night",
    "blurb": "A clever keeper calms angry monkeys just by changing how he counts their food.",
    "setting": "Long ago, at a monkey keeper's home in the countryside.",
    "characters": [
      "a clever monkey keeper with little food",
      "a group of hungry monkeys"
    ],
    "beats": [
      "The keeper runs low on food and must feed his monkeys fewer acorns.",
      "He offers three acorns in the morning and four at night, and the monkeys become angry.",
      "He switches to four in the morning and three at night, and the monkeys cheer.",
      "The total number of acorns is still seven, so nothing really changed.",
      "The monkeys' reaction shows how the same thing can feel different depending on how it is said."
    ],
    "themeHints": [
      "perception",
      "cleverness",
      "framing"
    ],
    "source": "work",
    "publicDomain": true,
    "attribution": "《庄子》 (Zhuangzi) — public domain"
  },
  {
    "id": "jing-ye-si",
    "title": "静夜思",
    "titleEn": "Quiet Night Thoughts",
    "blurb": "A traveler sees bright moonlight and feels a deep longing for home.",
    "setting": "A quiet bedroom at night, far from the poet's homeland.",
    "characters": [
      "a lonely traveler who misses his home",
      "the bright moon above"
    ],
    "beats": [
      "The traveler lies awake at night in a strange place far from home.",
      "He sees a patch of white light on the floor and mistakes it for frost.",
      "He lifts his head to look at the bright moon.",
      "He lowers his head as a deep ache of homesickness fills his heart."
    ],
    "themeHints": [
      "homesickness",
      "loneliness",
      "moonlight"
    ],
    "allowNames": [
      "李白"
    ],
    "source": "work",
    "publicDomain": true,
    "attribution": "李白《静夜思》 (Li Bai, \"Quiet Night Thoughts\") — public domain"
  },
  {
    "id": "deng-guan-que-lou",
    "title": "登鹳雀楼",
    "titleEn": "Climbing Stork Tower",
    "blurb": "A poet climbs a tall tower and discovers that going higher lets you see farther.",
    "setting": "Long ago in China, at a tall tower overlooking mountains and a great river.",
    "characters": [
      "a thoughtful poet who loves big views",
      "the tall Stork Tower with several floors"
    ],
    "beats": [
      "The poet climbs Stork Tower and looks out at the wide land.",
      "He watches the white sun sink behind the far mountains.",
      "He sees the Yellow River rushing onward toward the sea.",
      "He realizes that to see a thousand miles farther he must climb one more storey.",
      "He steps up and finds an even grander view waiting above."
    ],
    "themeHints": [
      "ambition",
      "perspective",
      "effort"
    ],
    "allowNames": [
      "王之涣",
      "鹳雀楼",
      "黄河"
    ],
    "source": "work",
    "publicDomain": true,
    "attribution": "王之涣《登鹳雀楼》 (Wang Zhihuan, \"Climbing Stork Tower\") — public domain"
  },
  {
    "id": "chun-xiao",
    "title": "春晓",
    "titleEn": "Spring Dawn",
    "blurb": "A poet wakes late on a spring morning, surrounded by birdsong, and wonders what the night storm has done to the flowers.",
    "setting": "A quiet house on a soft spring morning long ago.",
    "characters": [
      "a gentle poet who loves nature",
      "the birds singing all around the house"
    ],
    "beats": [
      "The poet sleeps late and wakes to bright spring light.",
      "From every side he hears birds singing loudly.",
      "He remembers a storm of wind and rain during the night.",
      "He wonders how many blossoms fell from the trees.",
      "He feels the quiet sadness of spring's fleeting beauty."
    ],
    "themeHints": [
      "beauty",
      "impermanence",
      "nature"
    ],
    "allowNames": [
      "孟浩然"
    ],
    "source": "work",
    "publicDomain": true,
    "attribution": "孟浩然《春晓》 (Meng Haoran, \"Spring Dawn\") — public domain"
  },
  {
    "id": "min-nong",
    "title": "悯农",
    "titleEn": "Sympathy for the Farmers",
    "blurb": "A midday scene in the field reveals the true cost of every bowl of rice.",
    "setting": "On a hot summer day at noon in a farmer's field.",
    "characters": [
      "a hardworking farmer hoeing the soil",
      "a person eating a bowl of rice at a table"
    ],
    "beats": [
      "The sun burns overhead while the farmer keeps hoeing his field.",
      "Sweat drips from his body and falls onto the soil.",
      "A person sits at a table and eats a full bowl of rice.",
      "The poem asks whether that eater knows each grain came from such hard work."
    ],
    "themeHints": [
      "gratitude",
      "labor",
      "cherishing food"
    ],
    "allowNames": [
      "李绅"
    ],
    "source": "work",
    "publicDomain": true,
    "attribution": "李绅《悯农》 (Li Shen, \"Sympathy for the Farmers\") — public domain"
  },
  {
    "id": "you-zi-yin",
    "title": "游子吟",
    "titleEn": "Song of the Wandering Son",
    "blurb": "A mother sews late into the night before her son leaves home, and he wonders how he can ever repay her love.",
    "setting": "In a simple home in ancient China, the night before a young man leaves on a long journey.",
    "characters": [
      "a loving, hardworking mother",
      "a grateful son who is about to travel far"
    ],
    "beats": [
      "A young man is preparing to leave home for a long journey.",
      "His mother sits up late, carefully stitching his travelling clothes by candlelight.",
      "She sews every stitch tight, afraid the clothes will wear out before he returns.",
      "The son watches her and feels deep gratitude for her endless care.",
      "He wonders how a small blade of grass could ever repay the warmth of the spring sun, just as he can never fully repay his mother's love."
    ],
    "themeHints": [
      "gratitude",
      "mother's love",
      "family"
    ],
    "allowNames": [
      "孟郊"
    ],
    "source": "work",
    "publicDomain": true,
    "attribution": "孟郊《游子吟》 (Meng Jiao, \"Song of the Wandering Son\") — public domain"
  },
  {
    "id": "shui-diao-ge-tou",
    "title": "水调歌头",
    "titleEn": "Prelude to Water Melody",
    "blurb": "A poet drinks under the bright Mid-Autumn moon and sends his wish across the distance to the people he loves.",
    "setting": "On a quiet rooftop in China during the Mid-Autumn Festival long ago.",
    "characters": [
      "a thoughtful poet who is far from his family",
      "the bright round moon shining alone in the sky",
      "loved ones far away whom the poet cannot see"
    ],
    "beats": [
      "The poet drinks alone on Mid-Autumn night and stares up at the bright full moon.",
      "He wonders when the moon first appeared and imagines flying up to the heavens.",
      "But he decides the cold sky is too lonely and chooses to stay in the warm human world.",
      "He cannot be with his loved ones, so he looks at the moon and sends them a wish.",
      "He hopes that everyone far apart may live long and share the same beautiful moon."
    ],
    "themeHints": [
      "separation",
      "longing",
      "hope"
    ],
    "allowNames": [
      "苏轼"
    ],
    "source": "work",
    "publicDomain": true,
    "attribution": "苏轼《水调歌头·明月几时有》 (Su Shi, \"Prelude to Water Melody\") — public domain"
  },
  {
    "id": "wang-lu-shan-pu-bu",
    "title": "望庐山瀑布",
    "titleEn": "Gazing at Lushan Waterfall",
    "blurb": "A traveler sees a great waterfall and imagines the sky itself is falling.",
    "setting": "Long ago in China, at a tall mountain with a famous peak called Incense-Burner Peak.",
    "characters": [
      "a quiet traveler who loves watching nature",
      "the huge waterfall on the cliff"
    ],
    "beats": [
      "The traveler stands below the mountain and watches the sun shine on the peak.",
      "The sunlight makes a soft purple mist rise above the rocks.",
      "Far away, a long waterfall hangs down the cliff like a white river.",
      "The water seems to fall from very high, as if the stars of the Milky Way were pouring from the sky.",
      "The traveler feels small and amazed at the power of nature."
    ],
    "themeHints": [
      "awe",
      "nature",
      "imagination"
    ],
    "allowNames": [
      "李白",
      "庐山"
    ],
    "source": "work",
    "publicDomain": true,
    "attribution": "李白《望庐山瀑布》 (Li Bai, \"Gazing at Lushan Waterfall\") — public domain"
  },
  {
    "id": "si-ma-guang-za-gang",
    "title": "司马光砸缸",
    "titleEn": "Sima Guang Breaks the Water Vat",
    "blurb": "When a playmate falls into a giant water vat, a calm boy must think fast to save him.",
    "setting": "In a garden in ancient China where a group of children are playing near a large water vat.",
    "characters": [
      "Sima Guang, a calm and clever boy",
      "a frightened playmate who falls into the water",
      "a group of panicked children"
    ],
    "beats": [
      "A group of children are playing together in a garden with a huge water vat.",
      "One boy climbs the vat, slips, and falls into the deep water.",
      "The other children panic and run away crying for help.",
      "Sima Guang stays calm, picks up a large rock, and smashes the vat.",
      "The water pours out, and the fallen child is saved."
    ],
    "themeHints": [
      "calmness",
      "quick-thinking",
      "courage"
    ],
    "allowNames": [
      "司马光"
    ],
    "source": "history"
  },
  {
    "id": "san-gu-mao-lu",
    "title": "三顾茅庐",
    "titleEn": "Three Visits to the Thatched Cottage",
    "blurb": "A powerful leader makes three humble journeys to win the help of a wise recluse.",
    "setting": "In ancient China during a time of war and divided kingdoms.",
    "characters": [
      "a kind and determined warlord who wants to bring peace",
      "a brilliant strategist who lives quietly in a thatched cottage",
      "the warlord's loyal brothers who doubt the visits are worth the trouble"
    ],
    "beats": [
      "The warlord hears that a great strategist lives in a remote cottage and sets out to invite him to help.",
      "On the first visit the strategist is away, so the warlord leaves disappointed but still hopeful.",
      "On the second visit, winter snow falls and the strategist is again absent, and the warlord's brothers urge him to give up.",
      "On the third visit the warlord waits patiently outside the cottage until the strategist wakes, showing true sincerity.",
      "Moved by the warlord's patience and respect, the strategist agrees to serve, and together they change the course of the age."
    ],
    "themeHints": [
      "sincerity",
      "persistence",
      "respect"
    ],
    "allowNames": [
      "刘备",
      "诸葛亮"
    ],
    "source": "history"
  },
  {
    "id": "fu-jing-qing-zui",
    "title": "负荆请罪",
    "titleEn": "Bearing Thorns to Beg Forgiveness",
    "blurb": "A proud soldier learns that his rival stayed calm for the good of their country, and he walks to the rival's door with thorns on his back to say sorry.",
    "setting": "Long ago in a Chinese kingdom where a brave general and a wise minister both serve the same king.",
    "characters": [
      "a proud and strong general who is quick to feel insulted",
      "a calm and wise minister who cares more about the country than his own pride",
      "the king they both serve"
    ],
    "beats": [
      "The minister wins great honor for the kingdom, and the general feels jealous and angry.",
      "The minister always avoids the general and stays away from him.",
      "The general learns the minister did this so the two of them would not fight and weaken the kingdom.",
      "Ashamed, the general bares his back, carries a bundle of thorns, and goes to the minister's gate to beg for punishment.",
      "The minister forgives him warmly, and the two become devoted friends."
    ],
    "themeHints": [
      "humility",
      "forgiveness",
      "common good"
    ],
    "allowNames": [
      "廉颇",
      "蔺相如"
    ],
    "source": "history"
  },
  {
    "id": "po-fu-chen-zhou",
    "title": "破釜沉舟",
    "titleEn": "Breaking the Cauldrons and Sinking the Boats",
    "blurb": "A general destroys his army's only way home, turning fear into fierce courage.",
    "setting": "Long ago in ancient China, two armies prepare for a decisive battle near a wide river.",
    "characters": [
      "a bold and determined general named Xiang Yu",
      "his large but worried army of soldiers",
      "a powerful enemy army waiting across the river"
    ],
    "beats": [
      "The general leads his army across a river to face a much larger enemy force.",
      "He orders his men to sink their boats and smash their cooking pots, leaving only three days of food.",
      "The soldiers realize there is no way to retreat, so they must win or perish.",
      "Filled with desperate courage, they fight far harder than ever before.",
      "They defeat the enemy army and win a great victory."
    ],
    "themeHints": [
      "commitment",
      "courage",
      "determination"
    ],
    "allowNames": [
      "项羽"
    ],
    "source": "history"
  },
  {
    "id": "cheng-men-li-xue",
    "title": "程门立雪",
    "titleEn": "Standing in the Snow at Cheng’s Door",
    "blurb": "Two students wait in the snow rather than wake their sleeping teacher.",
    "setting": "Long ago in China, at the home of a respected teacher during a snowy winter day.",
    "characters": [
      "a wise and respected teacher",
      "two eager and respectful students"
    ],
    "beats": [
      "Two students go to their teacher's home to ask him questions.",
      "They arrive and find their teacher asleep.",
      "They do not want to wake him, so they wait quietly outside in the snow.",
      "The teacher wakes later and finds them still waiting, with snow piled a foot deep.",
      "He is moved by their deep respect for him."
    ],
    "themeHints": [
      "respect",
      "patience",
      "devotion"
    ],
    "allowNames": [
      "杨时",
      "程颐"
    ],
    "source": "history"
  },
  {
    "id": "da-yu-zhi-shui",
    "title": "大禹治水",
    "titleEn": "Yu the Great Tames the Floods",
    "blurb": "A determined leader spends thirteen years guiding raging floodwaters to the sea, passing his own door without stopping.",
    "setting": "Ancient China, when great floods covered the land and destroyed homes and crops.",
    "characters": [
      "Yu, a determined and wise leader who takes charge of the flood crisis",
      "Yu's father, whose failed dam-building strategy could not stop the floods",
      "the suffering people whose villages and farmland are threatened by the water"
    ],
    "beats": [
      "Great floods cover the land, and Yu's father fails to stop them by building dams to block the water.",
      "Yu is chosen to solve the problem and decides to work with nature by dredging channels to guide the water to the sea.",
      "Yu labors for thirteen years, digging and organizing the people, and passes his own front door three times without going inside.",
      "The channels are completed and the floodwaters drain safely away, saving the people and the land."
    ],
    "themeHints": [
      "dedication",
      "cooperation",
      "perseverance"
    ],
    "allowNames": [
      "大禹"
    ],
    "source": "history"
  },
  {
    "id": "chun-jie",
    "title": "春节",
    "titleEn": "Spring Festival (Chinese New Year)",
    "blurb": "A fierce beast visits every New Year's Eve — until the villagers discover its one great weakness.",
    "setting": "Long ago in a Chinese village on the night before the new year.",
    "characters": [
      "a scary beast named Nian that comes out once a year to trouble the village",
      "a wise old visitor who knows the beast's secret",
      "the villagers who want to protect their families"
    ],
    "beats": [
      "Every New Year's Eve the beast Nian comes down from the hills and frightens the villagers.",
      "An old traveler arrives and tells the people that Nian is afraid of three things: the color red, bright fire, and loud noise.",
      "The villagers prepare by pasting red paper on their doors, lighting fires, and making noise with bamboo.",
      "When Nian appears, the red, firelight, and loud cracks drive it away for good.",
      "From then on, families gather each New Year's Eve for a reunion dinner, hang red couplets, and set off firecrackers to drive away bad luck and welcome the new year."
    ],
    "themeHints": [
      "family",
      "courage",
      "tradition"
    ],
    "allowNames": [
      "春节",
      "年兽"
    ],
    "source": "history"
  },
  {
    "id": "duan-wu-jie",
    "title": "端午节",
    "titleEn": "Dragon Boat Festival",
    "blurb": "A loyal poet's sacrifice inspires the festival traditions of dragon boats and zongzi.",
    "setting": "The story takes place long ago in the ancient state of Chu, by the Miluo River.",
    "characters": [
      "a loyal poet-minister who loves his country",
      "the people of Chu who admire the poet",
      "villagers who live near the river"
    ],
    "beats": [
      "The poet serves his state faithfully, but enemies make the ruler stop listening to him.",
      "When his state is defeated, the poet is so sad that he throws himself into the Miluo River.",
      "Villagers rush out in boats to save him, but they cannot find him in time.",
      "To keep fish away from his body, they throw rice into the water.",
      "Every year after, people remember him with boat races and rice dumplings."
    ],
    "themeHints": [
      "loyalty",
      "remembrance",
      "tradition"
    ],
    "allowNames": [
      "端午节",
      "屈原",
      "汨罗江"
    ],
    "source": "history"
  },
  {
    "id": "zhong-qiu-jie",
    "title": "中秋节",
    "titleEn": "Mid-Autumn Festival",
    "blurb": "Under the brightest full moon of the year, families share mooncakes and remember a legend of love separated by the sky.",
    "setting": "On a clear autumn night in China, during the Mid-Autumn Festival, with the year's roundest moon hanging overhead.",
    "characters": [
      "a family gathered together for the festival",
      "Chang'e, a woman who drank an elixir and floated to the moon",
      "Hou Yi, Chang'e's husband, a skilled archer left behind on Earth"
    ],
    "beats": [
      "On the night of the brightest full moon, a family sits together outdoors, eating round mooncakes and looking up at the sky.",
      "An elder tells the legend of Chang'e and Hou Yi, who were once a loving couple living on Earth.",
      "One day Chang'e swallowed a magical elixir of immortality and became weightless, floating up toward the moon.",
      "Hou Yi could only watch as his wife rose into the sky, and he was left behind, forever parted from her.",
      "The family finishes their mooncakes, understanding that the round moon and the round cakes stand for reunion and longing for those far away."
    ],
    "themeHints": [
      "reunion",
      "longing",
      "family"
    ],
    "allowNames": [
      "中秋节",
      "嫦娥",
      "后羿"
    ],
    "source": "history"
  },
  {
    "id": "qi-xi-jie",
    "title": "七夕节",
    "titleEn": "The Double Seventh Festival",
    "blurb": "Two lovers kept apart by a river of stars meet just once a year on a bridge of birds.",
    "setting": "The story happens in ancient China and reaches across the sky to the Milky Way.",
    "characters": [
      "a kind mortal cowherd who lives on earth",
      "a skilled weaver girl who lives in heaven",
      "a heavenly queen who separates the lovers as punishment",
      "many magpies that form a bridge across the sky"
    ],
    "beats": [
      "A poor cowherd and a heavenly weaver girl meet, fall in love, and marry.",
      "The heavenly queen becomes angry and takes the weaver girl back to the sky.",
      "The cowherd follows but the queen creates the Milky Way to keep them apart.",
      "Moved by their sadness, magpies fly up once a year to form a bridge.",
      "On the seventh night of the seventh month, the lovers reunite for one night."
    ],
    "themeHints": [
      "love",
      "faithfulness",
      "reunion"
    ],
    "allowNames": [
      "七夕节",
      "牛郎",
      "织女"
    ],
    "source": "history"
  },
  {
    "id": "qing-ming-jie",
    "title": "清明节",
    "titleEn": "Qingming (Tomb-Sweeping) Festival",
    "blurb": "A spring festival where families honor those who came before them and remember a loyal man's sacrifice.",
    "setting": "In China during springtime, when the land turns green and families go outdoors.",
    "characters": [
      "a family with children learning the old customs",
      "an elder who explains the meaning behind the festival",
      "Jie Zhitui, a loyal retainer who refused rewards and stayed on a mountain"
    ],
    "beats": [
      "In spring the family walks to the graves of their ancestors to sweep them clean and leave food as offerings.",
      "The elder tells the children about Jie Zhitui, who helped his lord long ago but asked for no reward.",
      "Jie Zhitui chose to stay hidden on a mountain rather than come down for fame or riches.",
      "To remember him, people once ate only cold food and did not light fires on this day.",
      "After the grave visit, the family enjoys the fresh spring greenery together, feeling both respect for the past and joy for new life."
    ],
    "themeHints": [
      "remembrance",
      "loyalty",
      "renewal"
    ],
    "allowNames": [
      "清明节",
      "介子推"
    ],
    "source": "history"
  },
  {
    "id": "chang-cheng",
    "title": "长城",
    "titleEn": "The Great Wall",
    "blurb": "A mighty wall was built to guard an empire, but behind its stones lies a woman's grief.",
    "setting": "Long ago in northern China, across mountains and deserts, over many dynasties.",
    "characters": [
      "a powerful emperor who orders the wall joined and extended",
      "a devoted wife whose husband is taken to build the wall",
      "the husband, a forced laborer who dies working on the wall"
    ],
    "beats": [
      "To stop northern raiders, rulers across many dynasties build and join long walls, especially under the First Emperor.",
      "A young husband is taken from his wife to work as a laborer on the wall.",
      "After long months, the husband dies from the harsh work before the wife can reach him.",
      "The wife travels to the wall and weeps bitterly for her lost husband.",
      "Her grief is so great that a stretch of the wall collapses, revealing the human cost behind the great wonder."
    ],
    "themeHints": [
      "monumental effort",
      "defense",
      "human cost"
    ],
    "allowNames": [
      "长城",
      "秦始皇",
      "孟姜女"
    ],
    "source": "history"
  },
  {
    "id": "bing-ma-yong",
    "title": "兵马俑",
    "titleEn": "The Terracotta Army",
    "blurb": "A silent army of clay soldiers waited underground for over two thousand years — then farmers digging a well changed history.",
    "setting": "Long ago in ancient China, near the city of Xi'an, at the tomb of the First Emperor.",
    "characters": [
      "the First Emperor of China, a powerful ruler who wanted protection even after death",
      "skilled craftworkers who shaped thousands of unique clay soldiers, horses, and chariots",
      "ordinary farmers who accidentally uncover the buried army while digging a well"
    ],
    "beats": [
      "The First Emperor commands thousands of life-sized clay soldiers, horses, and chariots to be made and buried near his tomb to guard him forever.",
      "Each clay soldier is given a different face, showing the amazing skill of the ancient craftworkers.",
      "The great clay army is sealed underground and forgotten for more than two thousand years.",
      "In 1974, farmers digging a well accidentally discover pieces of the buried soldiers.",
      "The hidden army is revealed to the world, astonishing everyone with its size, detail, and age."
    ],
    "themeHints": [
      "imperial power",
      "craftsmanship",
      "discovery"
    ],
    "allowNames": [
      "兵马俑",
      "秦始皇",
      "西安"
    ],
    "source": "history"
  },
  {
    "id": "gu-gong",
    "title": "故宫",
    "titleEn": "The Forbidden City",
    "blurb": "A forbidden palace of emperors becomes a palace for everyone.",
    "setting": "The story takes place in the heart of Beijing across five centuries of Chinese imperial rule and into the modern day.",
    "characters": [
      "a mighty emperor who rules from a golden-roofed palace",
      "common people who live outside the palace walls",
      "a modern-day visitor who walks through the palace gates"
    ],
    "beats": [
      "A powerful emperor builds a vast walled palace in the center of Beijing with golden roofs and endless courtyards.",
      "For five hundred years, Ming and Qing emperors live and rule inside, while common people are never allowed to enter.",
      "The empire ends and the old rulers leave the palace.",
      "The great gates are opened to everyone, and the forbidden place becomes a public museum.",
      "Today visitors from all over the world walk the same halls where only emperors once stood."
    ],
    "themeHints": [
      "grandeur",
      "history",
      "access"
    ],
    "allowNames": [
      "故宫",
      "北京"
    ],
    "source": "history"
  },
  {
    "id": "xi-hu",
    "title": "西湖",
    "titleEn": "West Lake",
    "blurb": "A misty lake in Hangzhou has sparked poems, bridges, and legends for hundreds of years.",
    "setting": "The story takes place around the beautiful West Lake in Hangzhou, China, across many centuries.",
    "characters": [
      "a famous poet-official named Su Shi who loves the lake",
      "the misty lake itself, surrounded by willows and arched bridges",
      "generations of poets and storytellers drawn to its beauty"
    ],
    "beats": [
      "People discover a shimmering lake ringed by green hills and soft mist.",
      "Poets visit the lake and write verses about its willows, water, and bridges.",
      "Su Shi, a poet who also serves as an official, builds a long causeway across the lake so people can enjoy it.",
      "Sites like Broken Bridge become the setting for beloved folk tales passed down through generations.",
      "The lake remains a place where nature, poetry, and legend are woven together forever."
    ],
    "themeHints": [
      "beauty",
      "poetry",
      "heritage"
    ],
    "allowNames": [
      "西湖",
      "杭州",
      "苏轼"
    ],
    "source": "history"
  },
  {
    "id": "huang-shan",
    "title": "黄山",
    "titleEn": "Mount Huang (the Yellow Mountains)",
    "blurb": "A great traveler climbs a famous mountain and discovers why people say no other mountains are needed after seeing it.",
    "setting": "Long ago in China, at the famous Yellow Mountains with their stone peaks and clouds.",
    "characters": [
      "a famous traveler who journeys across China to see every great mountain",
      "the mountain itself, with gnarled pines, hot springs, odd peaks, and seas of cloud"
    ],
    "beats": [
      "A traveler who has seen many famous mountains arrives at Mount Huang to judge it for himself.",
      "He climbs granite peaks where twisted pine trees cling to the bare rock.",
      "He bathes in hot springs and watches clouds roll like a sea below him.",
      "He realizes this mountain holds every kind of beauty he has ever sought.",
      "He declares that once a person has seen Mount Huang, no other mountains need be seen."
    ],
    "themeHints": [
      "wonder",
      "nature",
      "fulfillment"
    ],
    "allowNames": [
      "黄山",
      "徐霞客"
    ],
    "source": "history"
  },
  {
    "id": "qin-shi-huang",
    "title": "秦始皇",
    "titleEn": "Qin Shi Huang, the First Emperor",
    "blurb": "A fierce king unites a broken land, but his great deeds come at a cruel cost.",
    "setting": "The story takes place in ancient China during the Warring States period and the new unified empire, over two thousand years ago.",
    "characters": [
      "a young and ambitious king of Qin who dreams of uniting all lands",
      "rival rulers of the other warring states",
      "loyal generals and ministers who help him conquer and govern",
      "scholars and common people who suffer under his harsh laws"
    ],
    "beats": [
      "The young king of Qin fights many wars and defeats the rival states one by one.",
      "In 221 BC he declares himself the First Emperor of a united China.",
      "He orders one common writing system, one money, and one set of weights and measures so all people can understand and trade with each other.",
      "He joins old northern walls into one Great Wall to protect the empire, and builds a vast tomb guarded by a clay army.",
      "To stop criticism he burns books and kills scholars, and his harsh rule makes the people fear him even as they remember his great achievements."
    ],
    "themeHints": [
      "ambition",
      "unity",
      "cruelty"
    ],
    "allowNames": [
      "秦始皇"
    ],
    "source": "history"
  },
  {
    "id": "han-wu-di",
    "title": "汉武帝",
    "titleEn": "Emperor Wu of Han",
    "blurb": "A young emperor turns a threatened dynasty into a mighty empire and opens new roads to the world.",
    "setting": "The story takes place in ancient China during the Han dynasty, over two thousand years ago.",
    "characters": [
      "a young and ambitious emperor who wants to make his empire strong",
      "a brave young general who leads armies against northern raiders",
      "a loyal envoy who travels far to the west to find new friends and roads"
    ],
    "beats": [
      "The emperor takes power and wants his dynasty to be safe and great.",
      "Northern nomads called the Xiongnu have raided the empire for years, so the emperor sends bold young generals to defeat them.",
      "The emperor sends an envoy far to the west to find allies and discover new lands.",
      "The envoy's long journey opens trade routes that later become the Silk Road.",
      "The emperor also chooses Confucianism as the guiding teaching of the state, and the empire grows strong and united."
    ],
    "themeHints": [
      "ambition",
      "leadership",
      "vision"
    ],
    "allowNames": [
      "汉武帝",
      "匈奴",
      "张骞"
    ],
    "source": "history"
  },
  {
    "id": "huo-qu-bing",
    "title": "霍去病",
    "titleEn": "Huo Qubing, the Young General",
    "blurb": "A teenage general rides fast and far to defend his empire, then turns down a grand reward because his duty is not done.",
    "setting": "The story takes place long ago in the Han empire, on the northern frontier where the emperor's cavalry battles the Xiongnu horsemen.",
    "characters": [
      "a brave and talented young cavalry commander",
      "the emperor who trusts and rewards him",
      "the powerful Xiongnu horsemen who raid the empire's borders"
    ],
    "beats": [
      "A young man shows great talent as a cavalry leader and is given command of troops at a very early age.",
      "He leads fast surprise rides deep into enemy land and wins battle after battle against the Xiongnu.",
      "The emperor, pleased by the victories, offers him a fine mansion as a reward.",
      "The young general refuses, saying he cannot think of a comfortable home while the enemy is still undefeated.",
      "He keeps fighting for his country but falls ill and dies very young, remembered for his selfless devotion."
    ],
    "themeHints": [
      "duty",
      "selflessness",
      "courage"
    ],
    "allowNames": [
      "霍去病",
      "匈奴",
      "卫青"
    ],
    "source": "history"
  },
  {
    "id": "yue-fei",
    "title": "岳飞",
    "titleEn": "Yue Fei, the Loyal General",
    "blurb": "A great general carries his mother's words on his back and fights for a country that betrays him.",
    "setting": "In China during the Southern Song dynasty, when northern invaders threatened the land.",
    "characters": [
      "a brave and loyal young man who becomes a great general",
      "his loving mother who teaches him duty",
      "a jealous chancellor who plots against the general"
    ],
    "beats": [
      "Before he leaves home, his mother tattoos four words on his back commanding him to serve the country with perfect loyalty.",
      "He becomes a great general and wins many battles, driving the enemy armies back toward the north.",
      "Just as final victory is near, the jealous chancellor sends twelve urgent orders forcing the general to return.",
      "The chancellor falsely accuses the general, and the loyal general dies in prison far from the war he was winning.",
      "The people honor him forever as a national hero, and his mother's words become famous."
    ],
    "themeHints": [
      "loyalty",
      "injustice",
      "sacrifice"
    ],
    "allowNames": [
      "岳飞",
      "秦桧"
    ],
    "source": "history"
  },
  {
    "id": "zhu-ge-liang",
    "title": "诸葛亮",
    "titleEn": "Zhuge Liang, the Sage Strategist",
    "blurb": "A brilliant strategist gives everything to a leader who believed in him, even his last breath on the battlefield.",
    "setting": "In ancient China during the time of three rival kingdoms fighting for control of the land.",
    "characters": [
      "a wise and loyal strategist known for clever plans",
      "a humble leader who seeks out the strategist to help his cause",
      "the leader's young heir who inherits the mission"
    ],
    "beats": [
      "A humble leader visits a famous wise man three times and asks him to become his chief strategist.",
      "The wise man agrees and serves the leader with full devotion, using clever plans to win battles and build a kingdom.",
      "When the leader dies, the wise man promises to keep serving the leader's heir just as faithfully.",
      "He leads several difficult military campaigns against a powerful rival kingdom in the north.",
      "On his final campaign he grows weak and dies in the field, having given everything to the cause he believed in."
    ],
    "themeHints": [
      "loyalty",
      "wisdom",
      "devotion"
    ],
    "allowNames": [
      "诸葛亮",
      "刘备"
    ],
    "source": "history"
  },
  {
    "id": "guan-yu",
    "title": "关羽",
    "titleEn": "Guan Yu, the God of Loyalty",
    "blurb": "A warrior's loyalty to his sworn brother becomes a legend that outlives him and turns him into a god.",
    "setting": "In ancient China during the wars of the Three Kingdoms period, when rival lords fought to rule the land.",
    "characters": [
      "a brave and righteous general who never breaks his word",
      "a humble leader whom the general swears to serve as a brother",
      "a powerful enemy lord who attacks when the general is overextended",
      "the general's loyal soldiers who stand by him to the end"
    ],
    "beats": [
      "The general and the humble leader swear an oath of brotherhood, promising to live and die together.",
      "The general wins many battles with skill and courage, becoming famous across the land.",
      "He is given the task of guarding an important city while his sworn brother fights elsewhere.",
      "The enemy launches a surprise attack, and the general is surrounded and defeated.",
      "He refuses to surrender and dies loyal to his brother, and the people later worship him as a god of loyalty and war."
    ],
    "themeHints": [
      "loyalty",
      "honor",
      "brotherhood"
    ],
    "allowNames": [
      "关羽",
      "刘备",
      "荆州"
    ],
    "source": "history"
  },
  {
    "id": "kong-zi",
    "title": "孔子",
    "titleEn": "Confucius",
    "blurb": "A devoted teacher travels the land, sharing ideas about kindness and good government that will outlast empires.",
    "setting": "The story takes place in ancient China during a time of many rival states.",
    "characters": [
      "a wise and determined teacher",
      "loyal disciples who follow and learn from him",
      "rulers who listen but rarely change their ways"
    ],
    "beats": [
      "A curious boy loves learning and grows up to become a teacher.",
      "He opens his school to everyone, not just nobles, and teaches kindness, honesty, and proper conduct.",
      "He travels from state to state, hoping rulers will govern with virtue instead of force.",
      "Most rulers respect him but do not follow his advice, so he returns home to keep teaching.",
      "After his death, his disciples gather his sayings, and these words shape Chinese thought for over two thousand years."
    ],
    "themeHints": [
      "education",
      "virtue",
      "legacy"
    ],
    "allowNames": [
      "孔子"
    ],
    "source": "history"
  },
  {
    "id": "sun-wu",
    "title": "孙武",
    "titleEn": "Sun Tzu, Master of War",
    "blurb": "A great strategist proves that discipline works on anyone — even the king's own palace women.",
    "setting": "In ancient China during the Spring and Autumn period, in the kingdom of Wu.",
    "characters": [
      "a brilliant military strategist who believes discipline can be taught to anyone",
      "the king of Wu, who doubts the strategist's methods",
      "the king's palace women, who laugh and do not take orders seriously at first"
    ],
    "beats": [
      "The king asks the strategist to prove his skill by training his palace women as soldiers.",
      "The strategist gives clear orders, but the women laugh and do not obey.",
      "The strategist explains the rules again, but the women still laugh and treat it as a game.",
      "The strategist shows that discipline must have consequences and firmly restores order.",
      "The women finally march and obey every command perfectly, and the king sees that discipline works on anyone."
    ],
    "themeHints": [
      "discipline",
      "strategy",
      "leadership"
    ],
    "allowNames": [
      "孙武",
      "阖闾"
    ],
    "source": "history"
  },
  {
    "id": "feng-huo-xi-zhu-hou",
    "title": "烽火戏诸侯",
    "titleEn": "Fooling the Nobles with Beacon Fires",
    "blurb": "A king wastes his lords' trust for a laugh, and learns too late that trust cannot be relit.",
    "setting": "In ancient China, at the royal capital of the Western Zhou dynasty.",
    "characters": [
      "a king who wants to please his favorite queen",
      "a queen who rarely smiles but laughs when others are tricked",
      "loyal lords who rush to defend the capital when beacon fires are lit"
    ],
    "beats": [
      "The queen almost never smiles, so the king lights the warning beacon fires to trick his lords into rushing to the capital.",
      "The lords arrive only to find no enemy, and the queen laughs at their confusion, so the king does it again and again.",
      "When real enemies truly invade, the king lights the fires once more, but no lord comes to help.",
      "The capital falls and the dynasty ends, because the king had spent all the trust his lords once gave him."
    ],
    "themeHints": [
      "trust",
      "consequences",
      "responsibility"
    ],
    "allowNames": [
      "周幽王",
      "褒姒",
      "犬戎"
    ],
    "source": "history"
  },
  {
    "id": "chu-han-zheng-ba",
    "title": "楚汉争霸",
    "titleEn": "The Chu–Han Contention",
    "blurb": "Two rivals fight for the empire, but cunning and wise leadership prove stronger than might alone.",
    "setting": "Ancient China after the fall of the Qin dynasty, when rival warlords compete to rule the land.",
    "characters": [
      "Xiang Yu, a mighty and proud warrior who trusts his own strength",
      "Liu Bang, a shrewd and humble leader who knows how to use talented men",
      "Yu Ji, Xiang Yu's beloved companion",
      "Talented advisors and generals who choose sides as fortunes shift"
    ],
    "beats": [
      "After the Qin dynasty falls, Xiang Yu and Liu Bang both claim the right to rule the empire.",
      "Xiang Yu, the stronger fighter, wins many battles, but Liu Bang gathers wise advisors and skilled generals who help him grow stronger.",
      "At a tense feast, Xiang Yu nearly traps Liu Bang, but Liu Bang escapes through quick thinking and loyal friends.",
      "Over years of shifting fortunes, Liu Bang's wise use of talent slowly turns the tide against Xiang Yu's raw power.",
      "Surrounded at the river and hearing songs of his lost homeland on every side, Xiang Yu parts from Yu Ji and meets his end, while Liu Bang becomes emperor."
    ],
    "themeHints": [
      "character",
      "leadership",
      "talent"
    ],
    "allowNames": [
      "项羽",
      "刘邦",
      "虞姬"
    ],
    "source": "history"
  },
  {
    "id": "bei-shui-yi-zhan",
    "title": "背水一战",
    "titleEn": "Fighting with the River at Their Backs",
    "blurb": "When an army has no escape, every soldier fights like a hero.",
    "setting": "Long ago in China, at a narrow mountain pass where a river flows behind the battlefield.",
    "characters": [
      "a clever Han general who dares to break the rules of war",
      "his small, frightened army of loyal soldiers",
      "a powerful enemy king with a far larger army"
    ],
    "beats": [
      "The general leads his small army to a narrow pass where a huge enemy army waits.",
      "Instead of following the old war manuals, he orders his men to stand with a deep river right behind them.",
      "The soldiers realize there is no path to run away, so they feel both fear and resolve.",
      "When the enemy attacks, the trapped men fight with desperate courage and refuse to give ground.",
      "Against all odds, the small army shatters the larger force and wins a famous victory."
    ],
    "themeHints": [
      "courage",
      "desperation",
      "strategy"
    ],
    "allowNames": [
      "韩信",
      "井陉"
    ],
    "source": "history"
  },
  {
    "id": "han-xin-dian-bing",
    "title": "韩信点兵",
    "titleEn": "Han Xin Counts His Troops",
    "blurb": "A once-hungry outcast becomes China's greatest general, famous for a clever way to count any army and a bold answer about how many soldiers he can lead.",
    "setting": "The story takes place in ancient China during the founding of the Han dynasty.",
    "characters": [
      "a brilliant general who rose from poverty and humiliation",
      "an emperor who rules the new dynasty and tests his general with a question"
    ],
    "beats": [
      "A young man endures hunger and public humiliation but grows up to become the dynasty's greatest general.",
      "He invents a clever trick to count a huge army quickly by lining soldiers up in rows of different sizes and reading the remainders.",
      "The emperor asks how many troops a great leader can command.",
      "The emperor names a limit for himself, but the general answers that for him, the more soldiers the better.",
      "His bold reply reveals a genius for command that sets him apart from every other leader."
    ],
    "themeHints": [
      "genius",
      "confidence",
      "leadership"
    ],
    "allowNames": [
      "韩信",
      "刘邦"
    ],
    "source": "history"
  },
  {
    "id": "zhi-shang-tan-bing",
    "title": "纸上谈兵",
    "titleEn": "Theorizing Warfare on Paper",
    "blurb": "A young man who memorized every war book learns that real battles do not follow pages.",
    "setting": "Long ago in ancient China, two rival states are fighting over a place called Changping.",
    "characters": [
      "Zhao Kuo, a young man who can recite every war book but has never fought a real battle",
      "Lian Po, an old cautious general who prefers to defend and wait",
      "Bai Qi, a clever enemy general who sets a trap"
    ],
    "beats": [
      "Zhao Kuo studies war books day and night and can argue better than even his veteran father, but he has never led soldiers in battle.",
      "The king replaces the cautious old general Lian Po with Zhao Kuo, hoping for a quick victory.",
      "Confident in his book learning, Zhao Kuo orders a bold attack against the enemy.",
      "The enemy general Bai Qi pretends to retreat, then surrounds Zhao Kuo's entire army in a trap.",
      "The whole Zhao army is destroyed, proving that book knowledge without real experience can lead to disaster."
    ],
    "themeHints": [
      "experience",
      "overconfidence",
      "hubris"
    ],
    "allowNames": [
      "赵括",
      "廉颇",
      "白起",
      "长平"
    ],
    "source": "history"
  }
];
