import { parseArgs } from 'node:util';
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { z } from 'zod';
import { createLlmProvider } from '../lib/llm/index';
import type { StorySeed } from '../lib/seeds/types';
import { GENERATED_SEEDS } from '../lib/seeds/generated';
import { SEED_TOPICS, type SeedTopic } from '../data/seeds/topics';

// `pnpm gen:seeds` — offline, dev-time only. Drafts a StorySeed skeleton for each curated topic in
// data/seeds/topics.ts via the LLM and writes lib/seeds/generated.ts. The human curates the
// licensing-critical fields (source/attribution/allowNames); the model only fills the creative
// skeleton. Review the committed diff before merging. Not part of CI (needs a real key).
//
//   pnpm gen:seeds                 generate any topic missing from generated.ts (cheap re-run)
//   pnpm gen:seeds --force         regenerate every topic
//   pnpm gen:seeds --only <id>     (re)generate one topic, keep the rest

const SYSTEM_PROMPT = readFileSync(join(process.cwd(), 'prompts', 'seed.system.md'), 'utf8');
const OUT_PATH = join(process.cwd(), 'lib', 'seeds', 'generated.ts');

// The model fills these; the licensing-critical fields come from the curated topic.
const DraftSchema = z.object({
  blurb: z.string().min(1),
  setting: z.string().min(1),
  characters: z.array(z.string().min(1)).min(1),
  beats: z.array(z.string().min(1)).min(3).max(6),
  themeHints: z.array(z.string().min(1)).min(1).max(3),
});

/** Strip a leading/trailing markdown code fence if the model wrapped its JSON. */
function stripFence(raw: string): string {
  const t = raw.trim();
  if (!t.startsWith('```')) return t;
  return t
    .replace(/^```(?:json)?\s*/i, '')
    .replace(/\s*```$/, '')
    .trim();
}

async function draftSeed(llm: ReturnType<typeof createLlmProvider>, topic: SeedTopic): Promise<StorySeed> {
  if (topic.source === 'work' && !topic.attribution) {
    throw new Error(`topic "${topic.id}" is source:work but has no attribution`);
  }
  const user = [
    `Title (hanzi): ${topic.title}`,
    `Title (English): ${topic.titleEn}`,
    `Summary: ${topic.summary}`,
    '',
    'Return the JSON seed object.',
  ].join('\n');

  const res = await llm.generate({ system: SYSTEM_PROMPT, messages: [{ role: 'user', content: user }] });
  const parsed = DraftSchema.safeParse(JSON.parse(stripFence(res.text)));
  if (!parsed.success) {
    const issues = parsed.error.issues.map((i) => `${i.path.join('.') || '(root)'}: ${i.message}`).join('; ');
    throw new Error(`draft for "${topic.id}" failed validation: ${issues}`);
  }
  const draft = parsed.data;

  return {
    id: topic.id,
    title: topic.title,
    titleEn: topic.titleEn,
    blurb: draft.blurb,
    setting: draft.setting,
    characters: draft.characters,
    beats: draft.beats,
    themeHints: draft.themeHints,
    ...(topic.allowNames ? { allowNames: topic.allowNames } : {}),
    source: topic.source,
    ...(topic.source === 'work' ? { publicDomain: true, attribution: topic.attribution } : {}),
  };
}

function writeGenerated(seeds: StorySeed[]): void {
  const header =
    '// AUTO-GENERATED by `pnpm gen:seeds` from data/seeds/topics.ts — DO NOT EDIT BY HAND.\n' +
    '// Re-run the script (needs ANTHROPIC_API_KEY in .env) to (re)generate, then review the diff\n' +
    '// before committing.\n' +
    "import type { StorySeed } from './types';\n\n";
  const body = `export const GENERATED_SEEDS: StorySeed[] = ${JSON.stringify(seeds, null, 2)};\n`;
  writeFileSync(OUT_PATH, header + body);
}

async function main() {
  const { values } = parseArgs({ options: { force: { type: 'boolean' }, only: { type: 'string' } } });
  const force = values.force === true;
  const only = values.only as string | undefined;

  if (only && !SEED_TOPICS.some((t) => t.id === only)) {
    throw new Error(`--only "${only}" is not a topic id in data/seeds/topics.ts`);
  }

  // Seed from what's already on disk so non-target seeds are kept and progress survives a crash.
  const results = new Map(GENERATED_SEEDS.map((s) => [s.id, s]));
  const ordered = (): StorySeed[] => SEED_TOPICS.map((t) => results.get(t.id)).filter((s): s is StorySeed => !!s);

  const llm = createLlmProvider();
  const failures: string[] = [];

  for (const topic of SEED_TOPICS) {
    const isTarget = only ? topic.id === only : force || !results.has(topic.id);
    if (!isTarget) continue;
    process.stdout.write(`  drafting ${topic.id} (${topic.title}) … `);
    try {
      results.set(topic.id, await draftSeed(llm, topic));
      writeGenerated(ordered()); // persist after every success — a later failure can't undo it
      console.log('done');
    } catch (e) {
      failures.push(topic.id);
      console.log(`✗ ${e instanceof Error ? e.message : e}`);
    }
  }

  console.log(`\nWrote ${ordered().length} seed(s) to lib/seeds/generated.ts; ${failures.length} failed.`);
  if (failures.length > 0) {
    console.log(`Failed: ${failures.join(', ')}. Re-run \`pnpm gen:seeds\` to retry just these.`);
    process.exitCode = 1;
  } else {
    console.log('Review the diff before committing.');
  }
}

main().catch((e) => {
  console.error(e instanceof Error ? e.message : e);
  process.exitCode = 1;
});
